### ISSUE TITLE
Bunch of accessibility errors

### ISSUE THREAD

**Issue by mgifford** [usds/erap-guidance#7]
Sample of errors from https://usds.github.io/erap-guidance/

[AutomatedChecks_20210821_EmergencyRentalAssis.html.zip](https://github.com/usds/erap-guidance/files/7026271/AutomatedChecks_20210821_EmergencyRentalAssis.html.zip)

Found 189 errors on the site on some of these pages:

URL | Violations
-- | --
https://usds.github.io/erap-guidance/promising-practice-guides/forms/ | 34
https://usds.github.io/erap-guidance/outreach/ | 18
https://usds.github.io/erap-guidance/promising-practice-guides/program-web-sites/ | 15
https://usds.github.io/erap-guidance/ | 14
https://usds.github.io/erap-guidance/allocations-and-payments/ | 14
https://usds.github.io/erap-guidance/application-process/ | 14
https://usds.github.io/erap-guidance/faqs/ | 14
https://usds.github.io/erap-guidance/faqs/by-category/ | 14
https://usds.github.io/erap-guidance/faqs/changes/ | 14
https://usds.github.io/erap-guidance/program-index/ | 14
https://usds.github.io/erap-guidance/promising-practice-guides/ | 14
https://usds.github.io/erap-guidance/promising-practice-guides/application-prioritization/ | 14
https://usds.github.io/erap-guidance/promising-practice-guides/application-process/ | 14
https://usds.github.io/erap-guidance/promising-practice-guides/data/ | 14
https://usds.github.io/erap-guidance/promising-practice-guides/eviction-diversion/ | 14
https://usds.github.io/erap-guidance/promising-practice-guides/fact-specific-proxies/ | 14
https://usds.github.io/erap-guidance/promising-practice-guides/landlord-engagement/ | 14
https://usds.github.io/erap-guidance/promising-practice-guides/outreach/ | 14
https://usds.github.io/erap-guidance/promising-practice-guides/partnerships-in-program-implementation/ | 14
https://usds.github.io/erap-guidance/promising-practice-guides/strategies/ | 14
https://usds.github.io/erap-guidance/promising-practice-guides/utilities/ | 14
https://usds.github.io/ | 2
https://usds.github.io/about-treasury | 2
https://usds.github.io/data | 2
https://usds.github.io/erap-guidance/assets/forms/income/income-boston-Arabic.pdf | 2
https://usds.github.io/erap-guidance/assets/forms/income/income-boston-Portuguese.pdf | 2
https://usds.github.io/erap-guidance/era-data/grantee-urls-tribes | 2
https://usds.github.io/erap-guidance/implementation-guidance/changes/ | 2
https://usds.github.io/news/featured-stories | 2
https://usds.github.io/news/featured-stories/fact-sheet-the-american-rescue-plan-will-deliver-immediate-economic-relief-to-families | 2
https://usds.github.io/news/featured-stories/swearing-in-of-deputy-secretary-wally-adeyemo | 2
https://usds.github.io/news/press-releases | 2
https://usds.github.io/news/press-releases/jy0100 | 2
https://usds.github.io/news/press-releases/jy0101 | 2
https://usds.github.io/news/press-releases/jy0102 | 2
https://usds.github.io/news/press-releases/jy0103 | 2
https://usds.github.io/news/press-releases/jy0104 | 2
https://usds.github.io/news/press-releases/jy0105 | 2
https://usds.github.io/news/press-releases/jy0109 | 2
https://usds.github.io/news/press-releases/statements-remarks | 2
https://usds.github.io/policy-issues | 2
https://usds.github.io/search | 2
https://usds.github.io/services | 2
https://usds.github.io/services/the-multiemployer-pension-reform-act-of-2014 | 2
https://usds.github.io/services/the-multiemployer-pension-reform-act-of-2014/applications-for-benefit-suspension | 2
https://usds.github.io/services/the-multiemployer-pension-reform-act-of-2014/frequently-asked-questions-about-the-kline-miller-multiemployer-pension-reform-act | 2

**Comment by humancompanion-usds** [comment]
Thanks for this submission. This is a prototype of a sub-set of pages for Treasury's Emergency Rental Assistance program. The Treasury web team handles the actual build of the production site and uses this demonstration strictly for content and navigational recommendations. Thus this code does not ship to production. The Treasury web team checks their production code for accessibility issues.

**Comment by mgifford** [comment]
I understand. However even when establishing an MVP it is important to consider accessibility. Just like security issues, marking it a prototype doesn't avoid the problems.
